/** @typedef {{ command: string, description: string, usage?: string, ace?: string }} CommandEntry */

/** @type {Record<string, Record<string, unknown>>} */
export const docs = {
  "bmtb-bag-drugs": {
    acePermissions: [],
    requirements: [
      "ESX Legacy, QBCore, or Qbox",
      "ox_inventory or compatible inventory",
      "ox_target or qb-target",
      "ox_lib recommended",
    ],
    installSteps: [
      "Drop bmtb_bagdrugs into resources/[scripts]/ or [bmtb]/ and merge install items + icons.",
      "Ensure framework → ox_lib → inventory → target → bmtb_bagdrugs.",
      "Edit config.lua for package types, labels, and conversion amounts.",
      "ensure bmtb_bagdrugs — test packaging a raw item into a bag, jar, and bottle.",
    ],
    adminGuide: [
      "Merge packaging items and icons before first restart.",
      "Tune package types and conversion amounts in config.lua.",
      "Test one bag, one jar, and one bottle conversion before go-live.",
    ],
    playerCommands: [
      { command: "Packaging NUI", usage: "Target / item use", description: "Open the Bag Drugs menu — set quantity, take all, add, then confirm packaged output." },
      { command: "Raw product", usage: "Inventory", description: "Convert raw items into branded bags, jars, or prescription bottles." },
    ],
    adminCommands: [],
    notes: [
      "Tebex listing goes live August 15, 2026 at 12:00 PM ET.",
      "Pairs with BMTB Pill Press and BMTB Trap Phone for a full drug economy.",
    ],
    updateNotes: [
      "Advanced packaging — branded mylar bags, glass jars, and prescription bottles.",
      "Quantity NUI — add, take all, reset, and confirm exact package counts.",
      "Raw-to-packaged conversion — turn bulk product into labeled street-ready items.",
      "Configurable package types, labels, and batch sizes.",
      "Multi-framework — ESX Legacy, QBCore, and Qbox auto-detect.",
    ],
  },
  "bmtb-physical-therapy": {
    acePermissions: ["add_ace group.admin bmtb.ptadmin allow"],
    requirements: [
      "FiveM (Cerulean)",
      "Optional: wasabi_crutch + wasabi bridge/ambulance",
      "Optional: ox_target or qb-target",
      "Optional: ox_inventory (yoga mat item)",
      "Optional: ox_lib (Wasabi time query)",
    ],
    installSteps: [
      "Drop bmtb_physicaltherapy into resources/[scripts]/ or [bmtb]/.",
      "Open setup.html → Load config.lua → edit → Download → replace config.lua.",
      "Ensure Wasabi resources before bmtb_physicaltherapy if using Wasabi.",
      "Add ACE: add_ace group.admin bmtb.ptadmin allow",
      "Optional: merge install/ox_inventory_items.lua and copy yoga_mat.png to ox_inventory.",
      "ensure bmtb_physicaltherapy — /ptadmin to add PT location + therapy area (radius 4–6+).",
    ],
    adminGuide: [
      "Grant bmtb.ptadmin ACE before opening /ptadmin to staff.",
      "Create at least one PT location (ped) and therapy area with radius ≥ 4 (prefer 6).",
      "If using Wasabi, ensure wasabi_crutch starts before this resource.",
      "Smoke-test: notes → travel → place mat → exercises → complete + crutch clear.",
    ],
    playerCommands: [
      { command: "PT ped interaction", usage: "Target / E-key", description: "Talk to the physiotherapist, accept notes, and start a rehab session." },
      { command: "Therapy area", usage: "Map blip / GPS", description: "Travel to the configured area, place yoga mat, and complete exercise skill checks." },
      { command: "/ptuifix", description: "Clear stuck NUI cursor or focus if the UI locks up." },
    ],
    adminCommands: [
      { command: "/ptadmin", description: "Open admin panel — locations, areas, exercises, chains, settings, logs.", ace: "bmtb.ptadmin" },
      { command: "/ptcrutch [minutes] [id]", description: "Test crutch assignment (Wasabi or standalone).", ace: "bmtb.ptadmin" },
      { command: "/ptneed [injury]", description: "Assign therapy requirement to yourself (debug/admin).", ace: "bmtb.ptadmin" },
    ],
    notes: [
      "Admin ACE: bmtb.ptadmin",
      "Fresh installs ship data/locations.json as [] — place locations via /ptadmin.",
      "Set Config.Debug = false on production servers.",
    ],
    updateNotes: [
      "Yoga mat placement — place mat in therapy areas and run exercise chains.",
      "Skill-check exercises — easy difficulty, configurable laps, hold poses between checks.",
      "/ptadmin panel — locations, therapy areas, exercise chains, anim catalog, logs.",
      "Wasabi crutch bridge — optional PT-on-crutch flow with clear-on-complete.",
      "Built-in standalone crutch — streamed prop when Wasabi is off (GPLv3 credited).",
      "Multi-framework — ESX Legacy, QBCore, Qbox auto-detect; standalone core.",
      "setup.html — load/edit/download config.lua without hand-editing.",
    ],
  },
  "bmtb-real-money": {
    acePermissions: [],
    requirements: [
      "ESX Legacy, QBCore, or Qbox",
      "ox_inventory or compatible inventory",
      "ox_lib recommended",
      "oxmysql recommended",
    ],
    installSteps: [
      "Install bmtb_realmoney into resources/[scripts]/ or [bmtb]/.",
      "Merge bill items from install/*_items.lua into your inventory and copy icons.",
      "Ensure framework → ox_lib → inventory → bmtb_realmoney.",
      "Configure store register zones, floats, and dirty money in config.lua (or setup.html).",
      "ensure bmtb_realmoney — restart and test bill handoff, registers, and change-making.",
    ],
    adminGuide: [
      "Merge all bill denomination items before opening to players.",
      "Configure store zones and register starting floats in config.lua.",
      "If using /givecash, optionally add ACE: add_ace group.admin command.givecash allow (or your configured ACE).",
      "Test one register payment and one player-to-player handoff before go-live.",
    ],
    playerCommands: [
      { command: "/givecash", usage: "Optional ACE", description: "Hand physical cash bills to a nearby player with automatic change-making and animations." },
      { command: "Store registers", usage: "Target / E-key", description: "Pay at configured shop registers with real bill selection; registers make change and persist floats." },
      { command: "Inventory items", usage: "Use bill items", description: "Physical $1–$100 bills, clean and dirty money — no fake UI cash when framework mirror is enabled." },
    ],
    adminCommands: [],
    notes: [
      "Real cash. Real RP. No fake money.",
      "Optional bmtb_moneywash integration for dirty → clean flows.",
      "Tune register zones and dirty-money payouts before going live.",
    ],
    updateNotes: [
      "Real bill denominations — $1 through $100 with physical cash items.",
      "Clean & dirty money — separate flows with black-market dirty cash support.",
      "Automatic change-making — registers and handoffs calculate correct change.",
      "Player-to-player cash handoff — animations and bill exchange between players.",
      "Configurable store zones — place register points anywhere on your map.",
      "Steal registers & heists — server-side register theft for criminal RP.",
      "Multi-framework — ESX Legacy, QBCore, and Qbox auto-detect.",
    ],
  },
  "bmtb-scamming": {
    acePermissions: [],
    requirements: [
      "ESX Legacy (es_extended)",
      "ox_lib",
      "ox_inventory",
      "ox_target",
      "oxmysql",
      "Optional: bmtb_realmoney for physical cash payouts",
    ],
    installSteps: [
      "Install bmtb_scamming into resources/[scripts]/ or [bmtb]/.",
      "Run sql/full_install.sql or allow auto-migration on first start.",
      "Merge ox_inventory items from install files and copy images.",
      "Ensure es_extended → ox_lib → ox_inventory → ox_target → bmtb_scamming.",
      "Edit config.lua for payouts, heat, dispatch, ranks, and burn risk.",
      "ensure bmtb_scamming — test dump buy, encode, ATM cash-out, and sell run.",
    ],
    adminGuide: [
      "Import SQL and merge inventory items before first player join.",
      "Tune burn risk, police dispatch, and payout values in config.lua.",
      "Set Config.Debug to false on production servers.",
      "Test full loop: buy dump → encode card → ATM cash-out → sell run.",
    ],
    playerCommands: [
      { command: "/sellcards", description: "Start a street card-selling run — buyers spawn and purchase encoded cards for cash." },
      { command: "/stopsellcards", description: "Stop the active card sell run." },
      { command: "bmtb os laptop", usage: "Item / workstation", description: "Open scam laptop NUI — browse dumps, encode cards, check heat and rank." },
      { command: "ATM cash-out", usage: "Target ATM", description: "Use encoded cards at ATMs — decline, burn risk, and police dispatch may trigger." },
    ],
    adminCommands: [],
    notes: [
      "ESX Legacy only on v1.0 — QBCore is not supported yet.",
      "Tebex-only — no Gumroad listing for this script.",
      "Tune burn risk / police dispatch in config before going live.",
    ],
    updateNotes: [
      "Buy dumps — vendor flow for card data (Visa, MasterCard, etc.).",
      "Card encoder / programmer bench setup with streamed props.",
      "ATM cash-out with decline, burn risk, and police dispatch events.",
      "Heat + rank progression tied to scam activity.",
      "bmtb os laptop NUI for dump catalog, status, and operations.",
    ],
  },
  "bmtb-pillpress": {
    acePermissions: ["add_ace group.admin bmtb.pillpress.admin allow"],
    requirements: [
      "ESX Legacy, QBCore, or Qbox",
      "ox_inventory recommended (qb/ps/lj/qs/codem/core/ak47 supported)",
      "ox_target or qb-target",
      "Optional: bmtb_trapphone for street sell payouts",
    ],
    installSteps: [
      "Drop bmtb_pillpress into resources/[scripts]/ or [bmtb]/ and merge install/ items for your inventory.",
      "Copy html/img PNG icons into ox_inventory/web/images/ (filename = item id).",
      "Ensure framework, inventory, and target start before bmtb_pillpress.",
      "Add ACE: add_ace group.admin bmtb.pillpress.admin allow",
      "ensure bmtb_pillpress — edit config.lua for recipes, bottles, effects, demand, durability.",
      "Restart and test /pilladmin + /pilldemand. Optional trapphone for demand-based street payouts.",
    ],
    adminGuide: [
      "Add ACE bmtb.pillpress.admin (or configure FrameworkAdminGroups in config.lua).",
      "Merge install items and icons before first restart.",
      "Open /pilladmin after install — Tebex ships all pills Off; enable perks/visuals per pill.",
      "Test press placement, craft one batch, and fill a pill bottle before go-live.",
    ],
    playerCommands: [
      { command: "pill_press item", usage: "Inventory", description: "Place a pill press in the world — ghost placement, ground snap, craft batches." },
      { command: "/pilldemand", description: "Open street demand panel showing hot/cold pill types for this restart." },
      { command: "/unstuckpills", description: "Clear stuck pill use animations or sprint effects." },
      { command: "Pill / bottle items", usage: "Inventory", description: "Use pills for effects; fill, open, and withdraw pill bottles via metadata." },
    ],
    adminCommands: [
      { command: "/pilladmin", description: "Open staff pill admin panel — tune perks, visuals, and modes per pill type.", ace: "bmtb.pillpress.admin" },
    ],
    notes: [
      "ACE bmtb.pillpress.admin gates /pilladmin (framework admin fallback supported).",
      "Per-pill /pilladmin saves write to data/pill_admin_overrides.json.",
      "Trap phone integration needs both resources for demand-based sell payouts.",
    ],
    updateNotes: [
      "Placeable pill press — ghost placement, ground snap, one press per player until restart.",
      "Crafting — 10 pill types, configurable batch size, ingredient refund on fail/cancel.",
      "Pill bottles — fill, open, deposit, and withdraw via slot metadata.",
      "Street demand — hot/cold rotation each restart; BMTB UI panel via /pilldemand.",
      "Pill admin — /pilladmin NUI for per-pill perk/visual tuning.",
    ],
  },
  "bmtb-pods-2": {
    acePermissions: [],
    requirements: [
      "xsound (required — must start before pods)",
      "ESX Legacy or QBCore",
      "Inventory backend (ox_inventory / qb-inventory / auto-detect)",
    ],
    installSteps: [
      "Drop as bmtb_pods into resources/[scripts]/ or [bmtb]/.",
      "Ensure order: ensure xsound then ensure bmtb_pods.",
      "Add the bmtb_pods item to inventory; keep stream/ props intact.",
      "Framework/inventory bridges auto-register on most stacks.",
      "Restart xsound + bmtb_pods and test the item (fallback: /bmtbpods).",
    ],
    adminGuide: [
      "Always start xsound before bmtb_pods.",
      "Merge ox_inventory item with correct export fields.",
      "Verify stream/ assets load — missing props break the wearable UI.",
    ],
    playerCommands: [
      { command: "bmtb_pods item", usage: "Inventory", description: "Wear AirPods-style props and open the music NUI — volume, theme, playlist controls." },
      { command: "/bmtbpods", description: "Fallback command to open pods UI if item use fails." },
      { command: "/bmtbpodsoff", description: "Stop audio and close the pods session." },
    ],
    adminCommands: [
      { command: "/podsprop", description: "Prop debug tuner — adjust wearable prop offsets (dev/debug use)." },
    ],
    notes: [
      "No dedicated ACE — player item use only.",
      "Live resource name is bmtb_pods (not bmtb_airpods).",
      "Always start xsound before bmtb_pods.",
    ],
    updateNotes: [
      "AirPods-style personal music NUI with wearable streamed props.",
      "Dynamic theme colors with presets + custom hex picker.",
      "UI opens only when using pods; ESC/close + WASD while open.",
      "Requires xsound for audio playback.",
    ],
  },
  "bmtb-lean": {
    acePermissions: ["add_ace group.admin bmtb_lean.debug allow"],
    requirements: [
      "ESX Legacy (primary build)",
      "ox_lib",
      "oxmysql recommended",
      "ox_inventory or compatible inventory",
      "ox_target or qb-target (optional)",
    ],
    installSteps: [
      "Install bmtb_lean ESX build into [scripts]/ or [bmtb]/.",
      "Keep stream/ intact. Merge install items into inventory and copy images.",
      "Ensure order: ox_lib → es_extended → inventory → bmtb_lean.",
      "Edit config.lua for language, sip FX, props, thirst, notify duration.",
      "ensure bmtb_lean — ESX: /leanrebuildbaby if baby bottle metadata needs repair.",
    ],
    adminGuide: [
      "Merge all lean items and images before go-live.",
      "Set Config.Debug.clientCommands and serverCommands to false on production.",
      "Optional debug ACE bmtb_lean.debug for prop tuner and metadata repair tools only.",
      "Run /leanrebuildbaby once if migrating from an older lean build.",
    ],
    playerCommands: [
      { command: "/leancarry", description: "Toggle carrying your mixed lean cup in-hand with HUD (G drink / K add / X put away)." },
      { command: "Lean items", usage: "Inventory", description: "Pour baby bottles, mix purple/red/green variants, sip with FX, add ice and extras." },
    ],
    adminCommands: [
      { command: "/leanrebuildbaby", description: "ESX server — rebuild baby bottle metadata for all players (migration/repair).", ace: "bmtb_lean.debug" },
      { command: "/leantune", usage: "Debug only", description: "Prop tuner for cup/bottle attachments (requires Config.Debug.clientCommands = true).", ace: "bmtb_lean.debug" },
    ],
    notes: [
      "Debug ACE bmtb_lean.debug is optional (debug tools only).",
      "Config.Inventory.mode = auto probes supported backends on start.",
      "Start inventory before lean so items register correctly.",
    ],
    updateNotes: [
      "Lean bottle → baby bottle with line-based pouring.",
      "Double cup + Feyzo prep with mixed lean variants (purple / red / green).",
      "Hold / drink mixed lean with on-screen cup HUD.",
      "Custom prop attachments, streamed animations, and BMTB NUI menus.",
    ],
  },
  "bmtb-gofetch": {
    acePermissions: ["add_ace group.admin bmtb.gofetch.admin allow"],
    requirements: [
      "ox_lib",
      "oxmysql",
      "ESX Legacy / QBCore / Qbox",
      "ox_inventory, qb-inventory, or compatible inventory",
      "ox_target or qb-target (optional — E-key fallback)",
      "QBCore: qb-shops recommended for live catalogs",
    ],
    installSteps: [
      "Drop bmtb_gofetch into [bmtb]/ or [scripts]/ and merge install-me/ items + images.",
      "Ensure order: ox_lib → oxmysql → framework → inventory → (qb-shops if QB) → bmtb_gofetch.",
      "Add ACE: add_ace group.admin bmtb.gofetch.admin allow",
      "ensure bmtb_gofetch — restart inventory + GoFetch.",
      "Test with gofetch_tablet item — place order and receive NPC delivery.",
    ],
    adminGuide: [
      "Add ACE bmtb.gofetch.admin before staff testing.",
      "Start shops/inventory before GoFetch so live catalogs populate.",
      "Use /gofetchreloadshops after adding new shop inventory items.",
    ],
    playerCommands: [
      { command: "gofetch_tablet", usage: "Inventory item", description: "Open delivery tablet — browse live shop catalogs, pay cash/bank, place orders." },
      { command: "gofetch_package", usage: "Inventory / NPC", description: "Receive delivery package from burrito van courier when order arrives." },
    ],
    adminCommands: [
      { command: "/gofetchdebug", description: "Toggle admin debug logging for order/delivery pipeline.", ace: "bmtb.gofetch.admin" },
      { command: "/gofetchinstant", description: "Force instant delivery on next order (testing).", ace: "bmtb.gofetch.admin" },
      { command: "/gofetchorders", description: "List all active GoFetch orders in server console/chat.", ace: "bmtb.gofetch.admin" },
      { command: "/gofetchcancel [id]", description: "Cancel a player's active order by server ID.", ace: "bmtb.gofetch.admin" },
      { command: "/gofetchreloadshops", description: "Reload shop provider catalogs without full restart.", ace: "bmtb.gofetch.admin" },
    ],
    notes: [
      "Admin ACE: bmtb.gofetch.admin",
      "Start shops/inventory before GoFetch so catalogs populate.",
    ],
    updateNotes: [
      "Delivery tablet with live shop catalogs from ox_inventory and qb-shops.",
      "NPC burrito van courier fleet with optional GoFetch Express upgrades.",
      "Multi-framework ESX / QBCore / Qbox auto-detect.",
    ],
  },
  "bmtb-trapphone": {
    acePermissions: ["add_ace group.admin bmtb.trapphone.admin allow"],
    requirements: [
      "ESX Legacy (es_extended)",
      "ox_lib",
      "oxmysql",
      "ox_inventory",
      "ox_target (optional — E-key fallback)",
    ],
    installSteps: [
      "Drop bmtb_trapphone into resources/[scripts]/ and import SQL if provided.",
      "CRITICAL order: oxmysql → es_extended → ox_lib → bmtb_trapphone → ox_inventory.",
      "Add trap phone + drug items to ox_inventory/data/items.lua per ox_items.lua.",
      "Add ACE: add_ace group.admin bmtb.trapphone.admin allow",
      "ensure bmtb_trapphone — restart and test trap phone item + /trapphone.",
    ],
    adminGuide: [
      "Trap phone MUST start before ox_inventory or item exports will not register.",
      "Merge ox_items.lua entries — item names must match config.lua.",
      "Set Config.Debug and Config.DebugSales to false on live servers.",
      "Grant ACE bmtb.trapphone.admin to staff before opening economy.",
      "Test one street trap run and one delivery call before go-live.",
    ],
    playerCommands: [
      { command: "/trapphone", usage: "F6 keybind", description: "Open trap phone NUI when carrying a trap phone item." },
      { command: "trap phone item", usage: "Inventory", description: "Primary way to open phone — street trap, deliveries, plug contacts, rep." },
      { command: "Street trap", usage: "Phone UI", description: "Start auto or manual buyer runs — sell drugs, risk robbery, build street rep." },
      { command: "Delivery jobs", usage: "Phone UI", description: "Accept phone calls, deliver product to drop-off for payout." },
    ],
    adminCommands: [
      { command: "/trapadmin", description: "Print admin command help list.", ace: "bmtb.trapphone.admin" },
      { command: "/trapstatus [id]", description: "Show trap phone status for a player — rep, active run, debt, plugs.", ace: "bmtb.trapphone.admin" },
      { command: "/trapstop [id]", description: "Force-stop active trap run for a player.", ace: "bmtb.trapphone.admin" },
      { command: "/trapdeliverycancel [id]", description: "Cancel active delivery mission for a player.", ace: "bmtb.trapphone.admin" },
      { command: "/trapmeetupfail [id]", description: "Fail active plug meetup for a player.", ace: "bmtb.trapphone.admin" },
      { command: "/traprep [id] [units]", description: "Set street rep units sold for a player.", ace: "bmtb.trapphone.admin" },
      { command: "/trapbadrep [id] [amount|clear]", description: "Set or clear bad rep for a player.", ace: "bmtb.trapphone.admin" },
      { command: "/trapdebt [id] [plugId] [amount]", description: "Set plug tab debt for a player.", ace: "bmtb.trapphone.admin" },
      { command: "/trapcleardebt [id] [plugId]", description: "Clear plug tab debt (omit plugId for all plugs).", ace: "bmtb.trapphone.admin" },
      { command: "/trapgivephone [id] [item]", description: "Give a trap phone item to a player.", ace: "bmtb.trapphone.admin" },
      { command: "/trapreset [id]", description: "Wipe stats, rep, plugs, and messages — fresh start.", ace: "bmtb.trapphone.admin" },
    ],
    notes: [
      "Admin ACE: bmtb.trapphone.admin",
      "Must start BEFORE ox_inventory so item exports register.",
      "ESX Legacy only on current builds.",
    ],
    updateNotes: [
      "Street trap selling with auto/manual buyer modes and robbery risk.",
      "Delivery jobs via phone calls.",
      "Plug contacts, meetups, tab debt, and street rep ranks.",
      "Optional bmtb_pillpress demand integration for pill street payouts.",
    ],
  },
  "bmtb-strippers": {
    acePermissions: [
      "add_ace group.admin bmtb.strippers.admin allow",
      "add_ace group.admin bmtb_elevators.admin allow",
    ],
    requirements: [
      "ESX Legacy (primary build)",
      "ox_lib",
      "oxmysql",
      "ox_inventory recommended",
      "ox_target or qb-target",
      "esx_addonaccount",
      "Optional: bmtb_elevators (start AFTER strippers)",
    ],
    installSteps: [
      "Install bmtb_strippers ESX build into [scripts]/ or [bmtb]/.",
      "Import SQL (jobs + reputation) from sql/esx/.",
      "Add/refresh clubowner job and society account — run /refreshjobs.",
      "Ensure oxmysql → ox_lib → es_extended → inventory/target → bmtb_strippers.",
      "Add ACE: add_ace group.admin bmtb.strippers.admin allow",
      "If using elevators: ensure bmtb_strippers then bmtb_elevators + ACE bmtb_elevators.admin.",
      "Restart and test shifts, poles, VIP, /clubmanage.",
    ],
    adminGuide: [
      "Import all SQL files (install.sql, jobs.sql, reputation.sql) before first start.",
      "Grant bmtb.strippers.admin ACE to club managers and head staff.",
      "Configure club locations, poles, and VIP rooms in config.lua.",
      "Always start bmtb_strippers before bmtb_elevators if using elevator integration.",
      "Use /clubmanage to verify owner/staff workflows before opening club to public.",
    ],
    playerCommands: [
      { command: "/throwtip", description: "Throw cash tips at dancers during pole routines." },
      { command: "Club interactions", usage: "ox_target / E-key", description: "Clock in/out, pole dance, lap dances, VIP rooms, bar, and register interactions." },
    ],
    adminCommands: [
      { command: "/clubmanage", description: "Open club owner/manager panel — staff, finances, popularity.", ace: "bmtb.strippers.admin" },
      { command: "/setclubjob [id] [job]", description: "Assign club job to a player.", ace: "bmtb.strippers.admin" },
      { command: "/hirestripper [id]", description: "Hire a player as a stripper for the club.", ace: "bmtb.strippers.admin" },
      { command: "/firestripper [id]", description: "Fire a stripper from the club roster.", ace: "bmtb.strippers.admin" },
      { command: "/newpole", description: "Place a new pole at your current position.", ace: "bmtb.strippers.admin" },
      { command: "/removepole", description: "Remove nearest pole placement.", ace: "bmtb.strippers.admin" },
      { command: "/previewseat", description: "Preview lap dance seat placement.", ace: "bmtb.strippers.admin" },
      { command: "/previewstripper", description: "Preview stripper stage placement.", ace: "bmtb.strippers.admin" },
    ],
    notes: [
      "Admin ACE: bmtb.strippers.admin",
      "Always start bmtb_strippers before bmtb_elevators.",
      "Elevator admin ACE: bmtb_elevators.admin",
    ],
    updateNotes: [
      "Full strip club RP — shifts, poles, lap dances, VIP rooms, tips.",
      "Club owner management panel and popularity system.",
      "ESX society accounts and job integration.",
    ],
  },
  "bmtb-chains-as-items": {
    acePermissions: [],
    requirements: [
      "ox_lib",
      "ox_inventory (required)",
      "Optional clothing stream pack (ensure before bmtb_chains if provided)",
    ],
    installSteps: [
      "Drop bmtb_chains into resources/[scripts]/.",
      "Merge ox_inventory items + images from install files.",
      "Ensure ox_lib → ox_inventory → bmtb_chains.",
      "Configure jewelry shop zones in config.lua.",
      "ensure bmtb_chains — restart inventory + chains and test equip/shop.",
    ],
    adminGuide: [
      "Merge chain items with correct drawable/component metadata.",
      "Configure shop zones and prices in config.lua or setup.html.",
      "Test equip animation and stash-only transfer rules before go-live.",
    ],
    playerCommands: [
      { command: "chain items", usage: "Inventory", description: "Use chain items to equip jewelry on clothing component 7 with animations." },
      { command: "Jewelry shop", usage: "E-key zones", description: "Buy chains at configured shop locations." },
      { command: "/chainid", usage: "Debug", description: "Print current drawable/component ID for chain tuning." },
    ],
    adminCommands: [],
    notes: [
      "No dedicated ACE — item/shop driven.",
      "Live resource folder is bmtb_chains.",
      "Stash-only transfer rules reduce dump/dupe abuse.",
    ],
    updateNotes: [
      "Wearable jewelry chains using clothing component 7.",
      "E-key shop interaction and equip animations.",
      "ox_lib + ox_inventory focused install.",
    ],
  },
  "bmtb-loading-screen": {
    acePermissions: [],
    requirements: ["None — standalone loadscreen resource"],
    installSteps: [
      "Drop bmtb_loadingscreen into resources/ (often at root, not inside [qb]).",
      "Put videos/audio under assets/ and configure playlist/theme in CONFIG.",
      "ensure bmtb_loadingscreen EARLY in server.cfg (before oxmysql/core on many setups).",
      "Restart and verify the loadscreen appears on connect.",
    ],
    adminGuide: [
      "Replace asset files with your server branding before go-live.",
      "Ensure loadscreen starts early in server.cfg.",
      "Configure Discord/Tebex link blocks in CONFIG.",
      "No local ESX resource copy — verify assets after each Tebex update.",
    ],
    playerCommands: [],
    adminCommands: [],
    notes: [
      "No ACE required.",
      "Live resource name: bmtb_loadingscreen.",
      "Standalone — no framework dependency.",
    ],
    updateNotes: [
      "Video / YouTube playlist support with background audio.",
      "Themed UI with Discord / Tebex link blocks.",
      "Standalone — no framework dependency.",
    ],
  },
  "watermark-server-logo-script": {
    acePermissions: [],
    requirements: ["None — standalone client overlay"],
    installSteps: [
      "Drop watermark_logo (or your watermark resource) into [standalone]/.",
      "Replace the logo image asset with your server branding.",
      "ensure watermark_logo (or your resource name) in server.cfg.",
      "Restart and confirm the overlay appears in-game.",
    ],
    adminGuide: [
      "Swap logo PNG with your server branding.",
      "Tune position/opacity in resource config if available.",
      "No local ESX resource copy — verify overlay after Tebex download.",
    ],
    playerCommands: [],
    adminCommands: [],
    notes: ["No ACE required. Lightweight NUI watermark / server logo overlay."],
    updateNotes: [
      "Lightweight NUI watermark / server logo overlay.",
      "Standalone — no framework dependency.",
    ],
  },
  "bmtb-cooking": {
    acePermissions: [],
    requirements: [
      "ox_lib",
      "ESX Legacy",
      "ox_inventory",
      "ox_target",
    ],
    installSteps: [
      "Drop bmtb_cooking into [scripts]/ or [bmtb]/.",
      "Merge install items (install me/items_ox_inventory.lua).",
      "Ensure order: ox_lib → es_extended → ox_inventory → ox_target → bmtb_cooking.",
      "ensure bmtb_cooking — place stove / use world grills and test skill-check cook.",
    ],
    adminGuide: [
      "Merge portable stove item and cooking ingredients before go-live.",
      "Configure world grill locations and recipes in config.",
      "Test one portable stove placement and one world grill cook.",
    ],
    playerCommands: [
      { command: "portable_stove", usage: "Inventory item", description: "Place a portable stove and cook recipes with skill-check minigames." },
      { command: "World grills", usage: "ox_target / E-key", description: "Interact with configured world grill zones to cook." },
      { command: "/bmtb_potoffset", usage: "Debug", description: "Tune pot prop offset during development." },
    ],
    adminCommands: [],
    notes: ["No dedicated ACE on current builds.", "ESX Legacy only."],
    updateNotes: [
      "Placeable stove and world grill cooking.",
      "Skill-check cooking loops.",
      "Coke brick + crack style outputs (config driven).",
    ],
  },
  "bmtb-weapon-repair": {
    acePermissions: [],
    requirements: [
      "ox_lib",
      "oxmysql",
      "ESX or QBCore",
      "ox_inventory or compatible inventory exports",
    ],
    installSteps: [
      "Place bmtb_weaponrepair in resources/[scripts]/.",
      "Ensure ox_lib → oxmysql → framework → inventory → bmtb_weaponrepair.",
      "Import included SQL files and merge ox items if provided.",
      "ensure bmtb_weaponrepair — restart and test bench, crafting, repair.",
    ],
    adminGuide: [
      "Import SQL and gunsmith job data if using job-gated benches.",
      "Configure repair costs, farming zones, and bench locations in config.",
      "Test weapon repair and attachment crafting before go-live.",
    ],
    playerCommands: [
      { command: "/craft", usage: "At bench", description: "Open attachment crafting menu at a weapon bench." },
      { command: "Weapon bench", usage: "Target / item", description: "Repair weapons with configurable costs and animations." },
    ],
    adminCommands: [
      { command: "/placewbench", description: "Gunsmith job — place a weapon bench in the world.", ace: "Job: gunsmith" },
      { command: "/delwbench", description: "Gunsmith job — delete nearest placed weapon bench.", ace: "Job: gunsmith" },
    ],
    notes: [
      "Gunsmith bench commands are job-gated, not ACE-gated.",
      "Auto-detect weapons/ammo/attachments enabled by default.",
    ],
    updateNotes: [
      "Bench-based weapon repair with configurable costs.",
      "Attachment crafting system.",
      "Multi-framework ESX / QBCore auto-detect.",
    ],
  },
  "bmtb-wigs": {
    acePermissions: [],
    requirements: [
      "ox_lib",
      "ESX Legacy",
      "Inventory backend (ox / qb / auto)",
    ],
    installSteps: [
      "Drop bmtb_wigs into [scripts]/ or [bmtb]/.",
      "Merge install-me items/images into inventory.",
      "Ensure ox_lib → es_extended → inventory → bmtb_wigs.",
      "Set craft spots in config.lua then restart and test /wigsale.",
    ],
    adminGuide: [
      "Configure craft station coords in config.lua before go-live.",
      "Merge all wig items and craft ingredients.",
      "Test craft flow and one street sale run.",
    ],
    playerCommands: [
      { command: "/wigsale", description: "Start street wig selling — spawned customers approach to buy." },
      { command: "/wigstop", description: "Stop the active wig sale run." },
      { command: "Craft stations", usage: "Target / zones", description: "Craft wigs at configured station locations." },
      { command: "/wigzones", usage: "Debug", description: "Show configured sale/craft zone debug markers." },
    ],
    adminCommands: [],
    notes: ["No dedicated ACE on current builds.", "ESX Legacy only."],
    updateNotes: [
      "Wig craft stations with configurable spots.",
      "Street selling to spawned customers (/wigsale).",
      "Multi-inventory auto-detect.",
    ],
  },
  "bmtb-chopshop": {
    acePermissions: [],
    requirements: [
      "ox_lib",
      "oxmysql",
      "ESX or QBCore / Qbox",
      "bmtb-tasknotify (start before chopshop)",
      "bmtb-taskbar (start before chopshop)",
    ],
    installSteps: [
      "Install the [bmtbchopshop] pack: bmtb-tasknotify, bmtb-taskbar, bmtb_chopshop.",
      "Ensure order: framework → bmtb-tasknotify → bmtb-taskbar → bmtb_chopshop.",
      "Set marker/NPC/payout in bmtb_chopshop/config.lua.",
      "ensure each resource in order, then test a full chop run.",
    ],
    adminGuide: [
      "Always start bmtb-tasknotify and bmtb-taskbar before bmtb_chopshop.",
      "Configure chop locations, NPC, and payout in config.lua or setup.html.",
      "Enable PartChopDebugCommand in config only for development.",
      "Test one full part-chop payout before go-live.",
    ],
    playerCommands: [
      { command: "Chopshop location", usage: "NPC / marker", description: "Drive eligible vehicles to the chopshop — weld parts off for payout with taskbar UI." },
    ],
    adminCommands: [
      { command: "/bmtb_chop_debug", usage: "Config-gated", description: "Toggle part-chop debug logging (enable PartChopDebugCommand in config)." },
    ],
    notes: [
      "Always start tasknotify + taskbar before bmtb_chopshop.",
      "Uses BMTB taskbar + tasknotify helpers from [bmtbchopshop] pack.",
    ],
    updateNotes: [
      "Per-part welding chopshop gameplay.",
      "FX/sound sync with payout.",
      "Optional delete from player_vehicles / owned vehicles.",
    ],
  },
  "bmtb-tuning": {
    acePermissions: ["add_ace group.admin bmtb_tuning.admin allow"],
    requirements: [
      "ox_lib",
      "oxmysql",
      "ESX or QBCore",
      "ox_inventory or compatible inventory",
      "OneSync recommended",
    ],
    installSteps: [
      "Drop bmtb_tuning into [scripts]/.",
      "CRITICAL: ensure bmtb_tuning BEFORE ox_inventory.",
      "Ensure oxmysql → ox_lib → bmtb_tuning → framework → inventory.",
      "Add ACE: add_ace group.admin bmtb_tuning.admin allow",
      "Merge tuning_tablet item — test engine-sound NUI + persistence.",
    ],
    adminGuide: [
      "Start bmtb_tuning before ox_inventory so item exports register.",
      "Add sv_enableNetworkedScriptEntityStates true in server.cfg.",
      "Grant bmtb_tuning.admin ACE for diagnostic commands.",
      "Test tablet item and verify engine sound persists after restart.",
    ],
    playerCommands: [
      { command: "tuning_tablet", usage: "Inventory item", description: "Open engine-sound tuning NUI — apply and save per-vehicle audio." },
      { command: "/tuningplate", usage: "Debug", description: "Print/debug current vehicle plate for persistence testing." },
    ],
    adminCommands: [
      { command: "/tuningrefreshcache", description: "Refresh server-side tuning cache from database.", ace: "bmtb_tuning.admin" },
      { command: "/tuningcheck", description: "Run diagnostics on tuning persistence for nearby/current vehicle.", ace: "bmtb_tuning.admin" },
      { command: "/tuningowned", description: "List owned vehicles with saved tuning data.", ace: "bmtb_tuning.admin" },
    ],
    notes: ["Admin ACE: bmtb_tuning.admin", "Must start before ox_inventory."],
    updateNotes: [
      "Engine-sound tablet NUI with per-vehicle persistence.",
      "Mechanic online checks / job gates (config).",
      "Multi-framework inventory bridges.",
    ],
  },
  "bmtb-car-wipe": {
    acePermissions: ["add_ace group.admin bmtb_carwipe.admin allow"],
    requirements: [
      "ox_lib",
      "oxmysql",
      "Optional framework for notifies / ESX admin groups",
    ],
    installSteps: [
      "Drop bmtb_carwipe into [scripts]/ or [bmtb]/.",
      "Add ACE: add_ace group.admin bmtb_carwipe.admin allow (or set Config.Admins identifiers).",
      "Tune wipe interval, zones, and whitelist in config.lua or setup.html.",
      "ensure bmtb_carwipe after ox_lib/oxmysql — test auto wipe + /carwipe.",
    ],
    adminGuide: [
      "Configure at least one admin method: ACE, Config.Admins identifiers, or ESX admin groups.",
      "Set whitelisted zones for garages, dealerships, and player-owned areas.",
      "Test manual /carwipe with countdown before enabling aggressive auto-wipe intervals.",
    ],
    playerCommands: [],
    adminCommands: [
      { command: "/carwipe", description: "Start a manual vehicle wipe countdown.", ace: "bmtb_carwipe.admin" },
      { command: "/carwipe [seconds]", description: "Start wipe with custom countdown duration.", ace: "bmtb_carwipe.admin" },
      { command: "/carwipe cancel", description: "Cancel an in-progress wipe countdown.", ace: "bmtb_carwipe.admin" },
      { command: "/carwipe status", description: "Show current wipe timer and zone status.", ace: "bmtb_carwipe.admin" },
      { command: "carwipe", usage: "Server console", description: "Same as /carwipe but from server console (source 0).", ace: "bmtb_carwipe.admin" },
    ],
    notes: [
      "ACE: bmtb_carwipe.admin (Config.UseAcePermission = true by default).",
      "Also supports Config.Admins identifiers and ESX admin groups.",
    ],
    updateNotes: [
      "Auto + command vehicle wipe with NUI countdown.",
      "Whitelisted zones support.",
      "Admin via ACE, identifiers, or ESX admin groups.",
    ],
  },
  "bmtb-recycle-job": {
    acePermissions: [],
    requirements: [
      "ox_lib",
      "ESX Legacy / QBCore / Qbox",
      "ox_inventory recommended",
    ],
    installSteps: [
      "Drop bmtb_recyclingjob (or bmtb-recycle-job folder) into resources/[scripts]/.",
      "Add recycle_material and related items to your inventory.",
      "Ensure ox_lib → framework → inventory → recycling job resource.",
      "Add ensure bmtb_recyclingjob to server.cfg.",
      "Edit config.lua for yard location, payout, and blip settings.",
    ],
    adminGuide: [
      "Configure yard foreman NPC, sorting zones, and payout rates in config.lua.",
      "Add recycle items to inventory before go-live.",
      "No local ESX resource copy — verify install steps match your Tebex download folder name.",
      "Test clock-in → grab box → sort → sell loop once before opening job.",
    ],
    playerCommands: [
      { command: "Recycle yard", usage: "NPC / zones", description: "Clock in at foreman NPC, grab boxes, sort material, sell for cash payout." },
    ],
    adminCommands: [],
    notes: [
      "Resource folder may be bmtb_recyclingjob on server — match your Tebex download.",
      "No dedicated ACE — config-driven job locations and payouts.",
    ],
    updateNotes: [
      "Beginner-friendly recycling side hustle with foreman NPC.",
      "Sorting minigame and cash payouts.",
      "ESX / QBCore / Qbox support with ox_lib menus.",
    ],
  },
  "bmtb-givecar": {
    acePermissions: ["add_ace group.admin bmtb_givecar.command allow"],
    requirements: [
      "ox_lib",
      "oxmysql",
      "ESX (es_extended) or QBCore (qb-core)",
      "QB: qb-garages recommended",
    ],
    installSteps: [
      "Drop bmtb_givecar into [scripts]/ or [bmtb]/.",
      "Ensure framework + oxmysql + ox_lib before givecar.",
      "Add ACE: add_ace group.admin bmtb_givecar.command allow",
      "ensure bmtb_givecar — test /givecar, plane/boat/heli variants, /delcarplate.",
    ],
    adminGuide: [
      "Grant bmtb_givecar.command ACE to authorized staff.",
      "Configure AuthorizedRanks in config.lua as fallback.",
      "Run optional unique-plate SQL if your garage requires it.",
      "Test spawn, transfer, and delete flows before giving staff access.",
    ],
    playerCommands: [
      { command: "/givecar [id]", description: "Transfer ownership of the vehicle you are seated in to another player." },
    ],
    adminCommands: [
      { command: "/givecar me", description: "Spawn a vehicle for yourself (admin).", ace: "bmtb_givecar.command" },
      { command: "/givecar [id] [model]", description: "Spawn a vehicle model for a player.", ace: "bmtb_givecar.command" },
      { command: "/givecar offline [identifier] [model]", description: "Give a vehicle to an offline player by identifier.", ace: "bmtb_givecar.command" },
      { command: "/giveplane [id] [model]", description: "Spawn a plane for a player.", ace: "bmtb_givecar.command" },
      { command: "/giveboat [id] [model]", description: "Spawn a boat for a player.", ace: "bmtb_givecar.command" },
      { command: "/giveheli [id] [model]", description: "Spawn a helicopter for a player.", ace: "bmtb_givecar.command" },
      { command: "/delcarplate [plate]", description: "Delete a vehicle from the database by plate.", ace: "bmtb_givecar.command" },
      { command: "/listcars [id]", description: "List owned vehicles for a player.", ace: "bmtb_givecar.command" },
      { command: "/givecarmenu", description: "Open admin vehicle giveaway menu.", ace: "bmtb_givecar.command" },
    ],
    notes: [
      "Admin ACE: bmtb_givecar.command",
      "Also checks AuthorizedRanks in config.",
    ],
    updateNotes: [
      "Give / transfer / delete owned vehicles.",
      "Supports car, plane, boat, heli helpers.",
      "ACE + AuthorizedRanks gates.",
    ],
  },
  "bmtb-nocrosshair": {
    acePermissions: [],
    requirements: ["None — standalone client script"],
    installSteps: [
      "Drop bmtb_nocrosshair into [scripts]/ or [bmtb]/.",
      "ensure bmtb_nocrosshair (no config required on stock builds).",
      "Restart and confirm default GTA crosshair/reticle is hidden.",
    ],
    adminGuide: [
      "No configuration required for stock install.",
      "Players can toggle crosshair visibility with /crosshair if enabled in config.",
    ],
    playerCommands: [
      { command: "/crosshair", description: "Toggle personal crosshair/reticle visibility on or off." },
    ],
    adminCommands: [],
    notes: ["No ACE required.", "Client-only standalone resource."],
    updateNotes: [
      "Hides default GTA crosshair / reticle.",
      "Client-only standalone resource.",
    ],
  },
  "bmtb-itemslist": {
    acePermissions: ["add_ace group.admin bmtb_itemslist.admin allow"],
    requirements: [
      "ox_lib",
      "ESX or QBCore",
      "Inventory backend (ox / qb / multi-inventory bridge)",
    ],
    installSteps: [
      "Drop bmtb_itemslist into [scripts]/ or [bmtb]/.",
      "Ensure ox_lib → framework → inventory → bmtb_itemslist.",
      "Add ACE: add_ace group.admin bmtb_itemslist.admin allow",
      "Enable Config.UseAcePermission if using ACE gating.",
      "ensure bmtb_itemslist — open with /itemslist or configured keybind.",
    ],
    adminGuide: [
      "Grant bmtb_itemslist.admin ACE (or configure QBPermissions / AdminGroups).",
      "Enable audit logging in config if you want spawn tracking.",
      "Test spawn-to-self before giving full staff access.",
    ],
    playerCommands: [],
    adminCommands: [
      { command: "/itemslist", usage: "Page Down keybind", description: "Open admin item catalog NUI — search, spawn to self or others.", ace: "bmtb_itemslist.admin" },
    ],
    notes: [
      "ACE: bmtb_itemslist.admin (enable Config.UseAcePermission in config).",
      "QBPermissions / AdminGroups often used as fallback.",
    ],
    updateNotes: [
      "Admin item catalog NUI with spawn to self/others.",
      "Multi-framework inventory bridges.",
      "Audit log support on many builds.",
    ],
  },
  "bmtb-moneywash": {
    acePermissions: ["add_ace group.admin bmtb_moneywash.admin allow"],
    requirements: [
      "ox_lib",
      "oxmysql",
      "ESX / QBCore / Qbox (auto bridges)",
      "Inventory + ox_target or qb-target",
    ],
    installSteps: [
      "Drop bmtb_moneywash into [scripts]/ or [bmtb]/.",
      "Import bmtb_moneywash.sql (or allow auto CREATE on start).",
      "Ensure ox_lib → oxmysql → framework → inventory/target → bmtb_moneywash.",
      "Add ACE: add_ace group.admin bmtb_moneywash.admin allow",
      "ensure bmtb_moneywash — place washers with /moneywashplace and test wash flow.",
    ],
    adminGuide: [
      "Import SQL or allow auto-migration on first start.",
      "Grant bmtb_moneywash.admin ACE to staff who manage washer locations.",
      "Place at least one washer with /moneywashplace before opening to players.",
      "Configure wash fee and dirty-money item names in config.lua.",
    ],
    playerCommands: [
      { command: "Money wash prop", usage: "ox_target / E-key", description: "Interact with placed washer props — deposit dirty money, NUI progress, receive clean payout." },
    ],
    adminCommands: [
      { command: "/moneywashadd [model]", description: "Add a washer prop model to the placement list.", ace: "bmtb_moneywash.admin" },
      { command: "/moneywashremove [id]", description: "Remove a washer by database ID.", ace: "bmtb_moneywash.admin" },
      { command: "/moneywashprop", description: "Preview/adjust washer prop at your position.", ace: "bmtb_moneywash.admin" },
      { command: "/moneywashplace", description: "Ghost-place a new washer at your location (saved to MySQL).", ace: "bmtb_moneywash.admin" },
      { command: "/moneywashrefresh", description: "Reload all washer props from database.", ace: "bmtb_moneywash.admin" },
      { command: "/moneywashlist", description: "List all placed washers with IDs and fees.", ace: "bmtb_moneywash.admin" },
      { command: "/moneywashfee [id] [fee]", description: "Set wash fee percentage for a washer.", ace: "bmtb_moneywash.admin" },
    ],
    notes: [
      "Admin ACE: bmtb_moneywash.admin",
      "FrameworkAdminGroups fallback supported on many builds.",
      "Optional bmtb_realmoney integration for physical dirty cash.",
    ],
    updateNotes: [
      "Dirty → clean money wash with NUI progress.",
      "MySQL-backed washer locations + ghost placement.",
      "Multi-framework bridges.",
    ],
  },
};
