name: Lint

on:
  repository_dispatch:
    types:
      - vercel.deployment.ready

run-name: Vercel Lint - ${{ github.event.client_payload.project.name }}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      statuses: write

    steps:
      - name: Notify Vercel
        uses: vercel/repository-dispatch/actions/status@v1
        with:
          name: Vercel - bmtb-scripts: lint

      - name: Checkout
        uses: vercel/repository-dispatch/actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
